name: Check branch
on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: tuune/backend
      DOCKER_BUILDKIT: 1

    steps:
      - name: Get repo
        uses: actions/checkout@v2

      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: uk
      # - name: Create UK branch
      #   if: endsWith(github.ref, '/main')
      #   uses: peterjgrainger/action-create-branch@v2.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: uk

      - name: Create new release UK
        if: endsWith(github.ref, '/uk')
        id: create_release-uk
        uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter-uk.yml

      - name: Create new release US
        if: endsWith(github.ref, '/main')
        id: create_release-us
        uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter-us.yml
